on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pullrequest-trusted-helper:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: gardener/cc-utils/.github/actions/pullrequest-trust-helper@trusted-helper
    # uses: gardener/cc-utils/.github/workflows/pullrequest-trust-helper.yaml@trusted-helper
    # with:
    #  trusted-teams:
