on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pullrequest-trusted-helper:
    permissions:
      pull-requests: write
    uses: gardener/cc-utils/.github/workflows/pullrequest-trust-helper@trusted-helper
    with:
      trusted-teams:
